name: Markdown Validate

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "dependabot/npm_and_yarn/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.3

      - name: Markdown Linting Action
        uses: avto-dev/markdown-lint@v1.2.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: PHP Linting (Pint)
          skip_fetch: true
