name: Markdown Validate

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.3

      - name: Markdown Linting Action
        uses: avto-dev/markdown-lint@v1.2.0
